1- KUTUPHANELERIN ICE AKTARILMASI

In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

2- DOSYA YOLLARININ TANIMLANMASI

In [2]:
from pathlib import Path

# Notebook dosyası notebooks klasöründe olduğu için proje ana klasörüne çıkıyoruz.
PROJECT_ROOT = Path("..").resolve()

DATA_DIR = PROJECT_ROOT / "data"

RAW_DATA_PATH = DATA_DIR / "Dry_Bean_Dataset.xlsx"

CLEAN_DATA_PATH = DATA_DIR / "dry_bean_clean.csv"

READABLE_DATA_DIR = PROJECT_ROOT / "readable_data"
DATA_DIR.mkdir(exist_ok=True)
READABLE_DATA_DIR.mkdir(exist_ok=True)

X_TRAIN_PATH = DATA_DIR / "X_train.csv"
X_TEST_PATH = DATA_DIR / "X_test.csv"
Y_TRAIN_PATH = DATA_DIR / "y_train.csv"
Y_TEST_PATH = DATA_DIR / "y_test.csv"

X_TRAIN_SCALED_PATH = DATA_DIR / "X_train_scaled.csv"
X_TEST_SCALED_PATH = DATA_DIR / "X_test_scaled.csv"

print("Proje klasörü: ", PROJECT_ROOT)
print("Veri klasörü: ", RAW_DATA_PATH)

Proje klasörü:  C:\Users\AHMET ÇOLAK\Desktop\Veri_Bilimi_Proje
Veri klasörü:  C:\Users\AHMET ÇOLAK\Desktop\Veri_Bilimi_Proje\data\Dry_Bean_Dataset.xlsx

3- VERİ SETİNİN OKUNMASI

In [3]:
df = pd.read_excel(RAW_DATA_PATH)

print("Veri seti başarıyla yüklendi")
print("Veri boyutu: ", df.shape)

df.head()

Veri seti başarıyla yüklendi
Veri boyutu:  (13611, 17)

,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRation,Eccentricity,ConvexArea,EquivDiameter,Extent,Solidity,roundness,Compactness,ShapeFactor1,ShapeFactor2,ShapeFactor3,ShapeFactor4,Class
0,28395,610.291,208.178117,173.888747,1.197191,0.549812,28715,190.141097,0.763923,0.988856,0.958027,0.913358,0.007332,0.003147,0.834222,0.998724,SEKER
1,28734,638.018,200.524796,182.734419,1.097356,0.411785,29172,191.272750,0.783968,0.984986,0.887034,0.953861,0.006979,0.003564,0.909851,0.998430,SEKER
2,29380,624.110,212.826130,175.931143,1.209713,0.562727,29690,193.410904,0.778113,0.989559,0.947849,0.908774,0.007244,0.003048,0.825871,0.999066,SEKER
3,30008,645.884,210.557999,182.516516,1.153638,0.498616,30724,195.467062,0.782681,0.976696,0.903936,0.928329,0.007017,0.003215,0.861794,0.994199,SEKER
4,30140,620.134,201.847882,190.279279,1.060798,0.333680,30417,195.896503,0.773098,0.990893,0.984877,0.970516,0.006697,0.003665,0.941900,0.999166,SEKER

4- GENEL VERİ SETİNİN İNCELENMESİ

4.1- SÜTUNLAR VE VERİ TİPLERİ

In [4]:
print("Sütunlar:")
print(df.columns.tolist())

print("\nVeri tipleri:")
print(df.dtypes)

Sütunlar:
['Area', 'Perimeter', 'MajorAxisLength', 'MinorAxisLength', 'AspectRation', 'Eccentricity', 'ConvexArea', 'EquivDiameter', 'Extent', 'Solidity', 'roundness', 'Compactness', 'ShapeFactor1', 'ShapeFactor2', 'ShapeFactor3', 'ShapeFactor4', 'Class']

Veri tipleri:
Area                 int64
Perimeter          float64
MajorAxisLength    float64
MinorAxisLength    float64
AspectRation       float64
Eccentricity       float64
ConvexArea           int64
EquivDiameter      float64
Extent             float64
Solidity           float64
roundness          float64
Compactness        float64
ShapeFactor1       float64
ShapeFactor2       float64
ShapeFactor3       float64
ShapeFactor4       float64
Class                  str
dtype: object

4.2- İLK 5 SATIR

In [5]:

print("\nİlk 5 satır:")
pd.set_option("display.max_columns", None)  # Tüm sütunları göster
pd.set_option("display.width", 1000)  # Genişliği artır

display(df.head())

İlk 5 satır:

    Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  Class
0  28395    610.291       208.178117       173.888747      1.197191      0.549812       28715     190.141097  0.763923  0.988856   0.958027     0.913358      0.007332      0.003147      0.834222      0.998724  SEKER
1  28734    638.018       200.524796       182.734419      1.097356      0.411785       29172     191.272750  0.783968  0.984986   0.887034     0.953861      0.006979      0.003564      0.909851      0.998430  SEKER
2  29380    624.110       212.826130       175.931143      1.209713      0.562727       29690     193.410904  0.778113  0.989559   0.947849     0.908774      0.007244      0.003048      0.825871      0.999066  SEKER
3  30008    645.884       210.557999       182.516516      1.153638      0.498616       30724     195.467062  0.782681  0.976696   0.903936     0.928329      0.007017      0.003215      0.861794      0.994199  SEKER
4  30140    620.134       201.847882       190.279279      1.060798      0.333680       30417     195.896503  0.773098  0.990893   0.984877     0.970516      0.006697      0.003665      0.941900      0.999166  SEKER

4.3- İLK 5 SATIRIN TRANSPOZE GÖRÜNÜMÜ

In [6]:
df.head().T

                          0           1           2           3           4
Area                  28395       28734       29380       30008       30140
Perimeter           610.291     638.018      624.11     645.884     620.134
MajorAxisLength  208.178117  200.524796   212.82613  210.557999  201.847882
MinorAxisLength  173.888747  182.734419  175.931143  182.516516  190.279279
AspectRation       1.197191    1.097356    1.209713    1.153638    1.060798
Eccentricity       0.549812    0.411785    0.562727    0.498616     0.33368
ConvexArea            28715       29172       29690       30724       30417
EquivDiameter    190.141097   191.27275  193.410904  195.467062  195.896503
Extent             0.763923    0.783968    0.778113    0.782681    0.773098
Solidity           0.988856    0.984986    0.989559    0.976696    0.990893
roundness          0.958027    0.887034    0.947849    0.903936    0.984877
Compactness        0.913358    0.953861    0.908774    0.928329    0.970516
ShapeFactor1       0.007332    0.006979    0.007244    0.007017    0.006697
ShapeFactor2       0.003147    0.003564    0.003048    0.003215    0.003665
ShapeFactor3       0.834222    0.909851    0.825871    0.861794      0.9419
ShapeFactor4       0.998724     0.99843    0.999066    0.994199    0.999166
Class                 SEKER       SEKER       SEKER       SEKER       SEKER

4.4- TANIMLAYICI İSTATİSTİKLER

In [7]:
df.describe()

                Area     Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  Eccentricity     ConvexArea  EquivDiameter        Extent      Solidity     roundness   Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4
count   13611.000000  13611.000000     13611.000000     13611.000000  13611.000000  13611.000000   13611.000000   13611.000000  13611.000000  13611.000000  13611.000000  13611.000000  13611.000000  13611.000000  13611.000000  13611.000000
mean    53048.284549    855.283459       320.141867       202.270714      1.583242      0.750895   53768.200206     253.064220      0.749733      0.987143      0.873282      0.799864      0.006564      0.001716      0.643590      0.995063
std     29324.095717    214.289696        85.694186        44.970091      0.246678      0.092002   29774.915817      59.177120      0.049086      0.004660      0.059520      0.061713      0.001128      0.000596      0.098996      0.004366
min     20420.000000    524.736000       183.601165       122.512653      1.024868      0.218951   20684.000000     161.243764      0.555315      0.919246      0.489618      0.640577      0.002778      0.000564      0.410339      0.947687
25%     36328.000000    703.523500       253.303633       175.848170      1.432307      0.715928   36714.500000     215.068003      0.718634      0.985670      0.832096      0.762469      0.005900      0.001154      0.581359      0.993703
50%     44652.000000    794.941000       296.883367       192.431733      1.551124      0.764441   45178.000000     238.438026      0.759859      0.988283      0.883157      0.801277      0.006645      0.001694      0.642044      0.996386
75%     61332.000000    977.213000       376.495012       217.031741      1.707109      0.810466   62294.000000     279.446467      0.786851      0.990013      0.916869      0.834270      0.007271      0.002170      0.696006      0.997883
max    254616.000000   1985.370000       738.860153       460.198497      2.430306      0.911423  263261.000000     569.374358      0.866195      0.994677      0.990685      0.987303      0.010451      0.003665      0.974767      0.999733

5- EKSİK DEĞER KONTROLÜ

In [8]:
missing_values = df.isnull().sum()

print("Eksik değer sayilari:")
display(missing_values)

print("\nToplam eksik deger:", missing_values.sum())

Eksik değer sayilari:

Area               0
Perimeter          0
MajorAxisLength    0
MinorAxisLength    0
AspectRation       0
Eccentricity       0
ConvexArea         0
EquivDiameter      0
Extent             0
Solidity           0
roundness          0
Compactness        0
ShapeFactor1       0
ShapeFactor2       0
ShapeFactor3       0
ShapeFactor4       0
Class              0
dtype: int64

Toplam eksik deger: 0

6- TEKRARLI SATIR KONTROLÜ

In [9]:
duplicate_count = df.duplicated().sum()

print("Toplam tekrar eden satır sayısı:", duplicate_count)

Toplam tekrar eden satır sayısı: 68

7- TEKRARLI KAYITLARI TEMİZLEME

In [10]:
# Veri setinde 68 tekrarlı kayıt tespit edilmiştir.
# Analiz ve tutarlılık açısından bu tekrar eden veriler kaldırılacaktır.

df_clean = df.drop_duplicates().reset_index(drop=True)

print("Temizlik öncesi veri boyutu: ", df.shape)
print("Temizlik sonrası veri boyutu: ", df_clean.shape)
print("Kaldırılan tekrar eden kayıt sayısı: ", df.shape[0] - df_clean.shape[0])

Temizlik öncesi veri boyutu:  (13611, 17)
Temizlik sonrası veri boyutu:  (13543, 17)
Kaldırılan tekrar eden kayıt sayısı:  68

8- TEMİZ VERİYİ KAYDETME

In [11]:
df_clean.to_csv(CLEAN_DATA_PATH, index=False, encoding="utf-8-sig")

print("Temiz veri kaydedildi:")
print(CLEAN_DATA_PATH)

Temiz veri kaydedildi:
C:\Users\AHMET ÇOLAK\Desktop\Veri_Bilimi_Proje\data\dry_bean_clean.csv

9- ÖZELLİK VE HEDEF AYRIMI

In [12]:
X = df_clean.drop("Class", axis=1)
y = df_clean["Class"]

print("X boyutu:", X.shape)
print("y boyutu:", y.shape)

print("\nSınıflar:")
print(y.unique())

X boyutu: (13543, 16)
y boyutu: (13543,)

Sınıflar:
<StringArray>
['SEKER', 'BARBUNYA', 'BOMBAY', 'CALI', 'HOROZ', 'SIRA', 'DERMASON']
Length: 7, dtype: str

10- SINIF DAGILIMININ KONTROLU

In [13]:
class_counts = y.value_counts()

print("Sınıf dağılımı:")
print(class_counts)

Sınıf dağılımı:
Class
DERMASON    3546
SIRA        2636
SEKER       2027
HOROZ       1860
CALI        1630
BARBUNYA    1322
BOMBAY       522
Name: count, dtype: int64

11- EGITIM/TEST AYRIMI YAPILMASI

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("X_train boyutu:", X_train.shape)
print("X_test boyutu:", X_test.shape)
print("y_train boyutu:", y_train.shape)
print("y_test boyutu:", y_test.shape)

X_train boyutu: (10834, 16)
X_test boyutu: (2709, 16)
y_train boyutu: (10834,)
y_test boyutu: (2709,)

12- SINIF DAGILIMI KORUNMASI KONTROLU

In [15]:
print("Tüm veri sınıf oranları:")
print(y.value_counts(normalize=True).sort_index())

print("\nEğitim seti sınıf oranları:")
print(y_train.value_counts(normalize=True).sort_index())

print("\nTest seti sınıf oranları:")
print(y_test.value_counts(normalize=True).sort_index())

Tüm veri sınıf oranları:
Class
BARBUNYA    0.097615
BOMBAY      0.038544
CALI        0.120357
DERMASON    0.261833
HOROZ       0.137340
SEKER       0.149671
SIRA        0.194639
Name: proportion, dtype: float64

Eğitim seti sınıf oranları:
Class
BARBUNYA    0.097563
BOMBAY      0.038582
CALI        0.120362
DERMASON    0.261861
HOROZ       0.137345
SEKER       0.149622
SIRA        0.194665
Name: proportion, dtype: float64

Test seti sınıf oranları:
Class
BARBUNYA    0.097822
BOMBAY      0.038391
CALI        0.120340
DERMASON    0.261720
HOROZ       0.137320
SEKER       0.149871
SIRA        0.194537
Name: proportion, dtype: float64

13- ÖLÇEKLEME YAPILMASI

In [16]:
scaler = StandardScaler()

# Ölçekleme yalnızca eğitim verisine fit edilir.
# Test verisi, eğitim verisinden öğrenilen ortalama ve standart sapma kullanılarak dönüştürülür.
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_scaled = pd.DataFrame(X_train_scaled, columns=X.columns, index=X_train.index)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X.columns, index=X_test.index)

print("Ölçeklenmiş X_train boyutu:", X_train_scaled.shape)
print("Ölçeklenmiş X_test boyutu:", X_test_scaled.shape)

Ölçeklenmiş X_train boyutu: (10834, 16)
Ölçeklenmiş X_test boyutu: (2709, 16)

14- EĞİTİM/TEST DOSYALARININ KAYDEDİLMESİ

In [17]:
X_train.to_csv(X_TRAIN_PATH, index=False, encoding="utf-8-sig")
X_test.to_csv(X_TEST_PATH, index=False, encoding="utf-8-sig")

y_train.to_csv(Y_TRAIN_PATH, index=False, encoding="utf-8-sig")
y_test.to_csv(Y_TEST_PATH, index=False, encoding="utf-8-sig")

X_train_scaled.to_csv(X_TRAIN_SCALED_PATH, index=False, encoding="utf-8-sig")
X_test_scaled.to_csv(X_TEST_SCALED_PATH, index=False, encoding="utf-8-sig")

print("Tüm ortak veri dosyaları kaydedildi.")

Tüm ortak veri dosyaları kaydedildi.

15- OKUNABİLİR XLSX DOSYALARI OLUŞTURULMASI

In [18]:
# Excel'de daha okunabilir olması için ayrıca .xlsx dosyaları oluşturuyoruz.
# Bu dosyalar modelleme için zorunlu değildir, sadece insanlar tarafından okunması daha kolay olması içindir.

df_clean.to_excel(READABLE_DATA_DIR / "dry_bean_clean_okunabilir.xlsx", index=False)
X_train.to_excel(READABLE_DATA_DIR / "X_train_okunabilir.xlsx", index=False)
X_test.to_excel(READABLE_DATA_DIR / "X_test_okunabilir.xlsx", index=False)

y_train.to_frame(name="Class").to_excel(READABLE_DATA_DIR / "y_train_okunabilir.xlsx", index=False)
y_test.to_frame(name="Class").to_excel(READABLE_DATA_DIR / "y_test_okunabilir.xlsx", index=False)

X_train_scaled.to_excel(READABLE_DATA_DIR / "X_train_scaled_okunabilir.xlsx", index=False)
X_test_scaled.to_excel(READABLE_DATA_DIR / "X_test_scaled_okunabilir.xlsx", index=False)

print("Okunabilir Excel dosyaları oluşturuldu.")

Okunabilir Excel dosyaları oluşturuldu.

16- SON KONTROLLER

In [19]:
saved_files = [
    CLEAN_DATA_PATH,
    X_TRAIN_PATH,
    X_TEST_PATH,
    Y_TRAIN_PATH,
    Y_TEST_PATH,
    X_TRAIN_SCALED_PATH,
    X_TEST_SCALED_PATH,
    
    READABLE_DATA_DIR / "dry_bean_clean_okunabilir.xlsx",
    READABLE_DATA_DIR / "X_train_okunabilir.xlsx",
    READABLE_DATA_DIR / "X_test_okunabilir.xlsx",
    READABLE_DATA_DIR / "y_train_okunabilir.xlsx",
    READABLE_DATA_DIR / "y_test_okunabilir.xlsx",
    READABLE_DATA_DIR / "X_train_scaled_okunabilir.xlsx",
    READABLE_DATA_DIR / "X_test_scaled_okunabilir.xlsx",
]

for file_path in saved_files:
    if file_path.exists():
        print(f"{file_path.name} başarıyla kaydedildi.")
    else:
        print(f"{file_path.name} kaydedilemedi!")

dry_bean_clean.csv başarıyla kaydedildi.
X_train.csv başarıyla kaydedildi.
X_test.csv başarıyla kaydedildi.
y_train.csv başarıyla kaydedildi.
y_test.csv başarıyla kaydedildi.
X_train_scaled.csv başarıyla kaydedildi.
X_test_scaled.csv başarıyla kaydedildi.
dry_bean_clean_okunabilir.xlsx başarıyla kaydedildi.
X_train_okunabilir.xlsx başarıyla kaydedildi.
X_test_okunabilir.xlsx başarıyla kaydedildi.
y_train_okunabilir.xlsx başarıyla kaydedildi.
y_test_okunabilir.xlsx başarıyla kaydedildi.
X_train_scaled_okunabilir.xlsx başarıyla kaydedildi.
X_test_scaled_okunabilir.xlsx başarıyla kaydedildi.