1- KÜTÜPHANELER VE DOSYA YOLLARI

In [1]:
import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path("..").resolve()

RESULTS_DIR = PROJECT_ROOT / "reports" / "results"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

KISI1_RESULTS_PATH = RESULTS_DIR / "kisi1_model_sonuclari.csv"
KISI2_RESULTS_PATH = RESULTS_DIR / "kisi2_model_sonuclari.csv"
ALL_RESULTS_PATH = RESULTS_DIR / "tum_model_sonuclari.csv"

print("Proje klasörü:", PROJECT_ROOT)
print("Sonuç klasörü:", RESULTS_DIR)

Proje klasörü: C:\Users\AHMET ÇOLAK\Desktop\Veri_Bilimi_Proje
Sonuç klasörü: C:\Users\AHMET ÇOLAK\Desktop\Veri_Bilimi_Proje\reports\results

2- KİŞİ1 VE KİŞİ2 SONUÇLARININ OKUNMASI

In [2]:
kisi1_results = pd.read_csv(KISI1_RESULTS_PATH)
kisi2_results = pd.read_csv(KISI2_RESULTS_PATH)

print("Kişi 1 sonuçları:")
display(kisi1_results)

print("Kişi 2 sonuçları:")
display(kisi2_results)

Kişi 1 sonuçları:

,Model,Accuracy,Weighted Precision,Weighted Recall,Weighted F1-score
0,KNN,0.915467,0.916315,0.915467,0.915652
1,Decision Tree,0.895533,0.895365,0.895533,0.895289
2,Gaussian Naive Bayes,0.763012,0.764673,0.763012,0.760651

Kişi 2 sonuçları:

,Model,Accuracy,Weighted Precision,Weighted Recall,Weighted F1-score
0,YSA,0.927649,0.927733,0.927649,0.927664
1,SVM,0.921004,0.921411,0.921004,0.921078
2,Random Forest,0.916944,0.917019,0.916944,0.916887

3- SÜTUN ADLARININ KONTROLÜ

In [3]:
print("Kişi 1 sütunları:")
print(kisi1_results.columns.tolist())

print("\nKişi 2 sütunları:")
print(kisi2_results.columns.tolist())

Kişi 1 sütunları:
['Model', 'Accuracy', 'Weighted Precision', 'Weighted Recall', 'Weighted F1-score']

Kişi 2 sütunları:
['Model', 'Accuracy', 'Weighted Precision', 'Weighted Recall', 'Weighted F1-score']

4- STANDART HÜCRE SUTUN SIRASININ UYGULANMASI

In [4]:
standard_columns = [
    "Model",
    "Accuracy",
    "Weighted Precision",
    "Weighted Recall",
    "Weighted F1-score"
]

kisi1_results = kisi1_results[standard_columns]
kisi2_results = kisi2_results[standard_columns]

5- SONUÇLARIN BİRLEŞTİRİLMESİ

In [5]:
all_results = pd.concat(
    [kisi1_results, kisi2_results],
    ignore_index=True
)

print("Birleştirilmiş sonuçlar:")
display(all_results)

Birleştirilmiş sonuçlar:

,Model,Accuracy,Weighted Precision,Weighted Recall,Weighted F1-score
0,KNN,0.915467,0.916315,0.915467,0.915652
1,Decision Tree,0.895533,0.895365,0.895533,0.895289
2,Gaussian Naive Bayes,0.763012,0.764673,0.763012,0.760651
3,YSA,0.927649,0.927733,0.927649,0.927664
4,SVM,0.921004,0.921411,0.921004,0.921078
5,Random Forest,0.916944,0.917019,0.916944,0.916887

6- WEİGHTED F1-SCORE'A GÖRE SIRALAMA

In [6]:
all_results_sorted = all_results.sort_values(
    by="Weighted F1-score",
    ascending=False
).reset_index(drop=True)

print("Weighted F1-score değerine göre sıralanmış sonuçlar:")
display(all_results_sorted)

Weighted F1-score değerine göre sıralanmış sonuçlar:

,Model,Accuracy,Weighted Precision,Weighted Recall,Weighted F1-score
0,YSA,0.927649,0.927733,0.927649,0.927664
1,SVM,0.921004,0.921411,0.921004,0.921078
2,Random Forest,0.916944,0.917019,0.916944,0.916887
3,KNN,0.915467,0.916315,0.915467,0.915652
4,Decision Tree,0.895533,0.895365,0.895533,0.895289
5,Gaussian Naive Bayes,0.763012,0.764673,0.763012,0.760651

7- EN İYİ MODELİN BELİRLENMESİ

In [7]:
best_model = all_results_sorted.iloc[0]

print("En iyi model:")
print("Model:", best_model["Model"])
print("Accuracy:", best_model["Accuracy"])
print("Weighted Precision:", best_model["Weighted Precision"])
print("Weighted Recall:", best_model["Weighted Recall"])
print("Weighted F1-score:", best_model["Weighted F1-score"])

En iyi model:
Model: YSA
Accuracy: 0.9276485788113696
Weighted Precision: 0.9277330600851514
Weighted Recall: 0.9276485788113696
Weighted F1-score: 0.9276637172948544

8- FİNAL SONUÇLARININ KAYDEDİLMESİ

In [8]:
all_results_sorted.to_csv(
    ALL_RESULTS_PATH,
    index=False,
    encoding="utf-8-sig"
)

print("Tüm model sonuçları kaydedildi:")
print(ALL_RESULTS_PATH)

Tüm model sonuçları kaydedildi:
C:\Users\AHMET ÇOLAK\Desktop\Veri_Bilimi_Proje\reports\results\tum_model_sonuclari.csv

9- KAYDEDİLEN DOSYANIN TEKRAR OKUNMASI VE KONTROL EDİLMESİ

In [9]:
kontrol_df = pd.read_csv(ALL_RESULTS_PATH)

print("Kaydedilen final sonuç tablosu:")
display(kontrol_df)

Kaydedilen final sonuç tablosu:

,Model,Accuracy,Weighted Precision,Weighted Recall,Weighted F1-score
0,YSA,0.927649,0.927733,0.927649,0.927664
1,SVM,0.921004,0.921411,0.921004,0.921078
2,Random Forest,0.916944,0.917019,0.916944,0.916887
3,KNN,0.915467,0.916315,0.915467,0.915652
4,Decision Tree,0.895533,0.895365,0.895533,0.895289
5,Gaussian Naive Bayes,0.763012,0.764673,0.763012,0.760651

10- SON KONTROL

In [10]:
print("Kişi 1 sonuç dosyası var mı?", KISI1_RESULTS_PATH.exists())
print("Kişi 2 sonuç dosyası var mı?", KISI2_RESULTS_PATH.exists())
print("Tüm sonuçlar dosyası var mı?", ALL_RESULTS_PATH.exists())

print("\nModel sayısı:", len(kontrol_df))
print("Model listesi:")
print(kontrol_df["Model"].tolist())

Kişi 1 sonuç dosyası var mı? True
Kişi 2 sonuç dosyası var mı? True
Tüm sonuçlar dosyası var mı? True

Model sayısı: 6
Model listesi:
['YSA', 'SVM', 'Random Forest', 'KNN', 'Decision Tree', 'Gaussian Naive Bayes']